apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: api
    path: api-deploy-patch-replicas.yaml
  - target:
      kind: Deployment
      name: api
    path: api-deploy-add-resources.yaml
  - target:
      kind: Deployment
      name: web
    path: web-deploy-patch-replicas.yaml
  - target:
      kind: Deployment
      name: web
    path: web-deploy-add-resources.yaml
  - target:
      kind: Deployment
      name: web
    path: remove-diag-container.yaml
  - path: api-deploy-add-pod-container-scc.yaml
  - path: web-deploy-add-pod-container-scc.yaml