apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-shop-ing
  namespace: ing-lab2
spec:
  ingressClassName: cilium
  rules:
  - host: "internal.shop.local"
    http:
      paths:
      - pathType: Exact
        path: "/"
        backend:
          service:
            name: admin
            port:
              number: 80