apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <html>
      <head><title>Kustomize Lab</title></head>
      <body>
        <h1>Kustomize Lab - Base</h1>
        <p>If you can see this page, the web Deployment mounted a ConfigMap.</p>
      </body>
    </html>
