apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap-app.yaml
  - configmap-web.yaml
  - api-deploy.yaml
  - web-deploy.yaml
  - api-svc.yaml
  - web-svc.yaml

namespace: kust-lab

configMapGenerator:
  - name: app-config
    envs:
      - app.env